name: Deploy (tag)

on:
  push:
    tags:
      - 'v*'        # e.g. v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy over SSH (key)
        continue-on-error: true
        uses: appleboy/ssh-action@v1.2.1
        env:
          TAG: ${{ github.ref_name }}
          APP_DIR: /var/www/html/snipeit
          REPO_URL: git@github.com:BZ1884/snipe-it.git
          PHP_FPM_SERVICE: php8.3-fpm   # adjust if needed
          APACHE_SERVICE: apache2
          KEEP_RELEASES: "5"
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script_stop: true
          envs: TAG,APP_DIR,REPO_URL,PHP_FPM_SERVICE,APACHE_SERVICE,KEEP_RELEASES
          script: |
            bash /var/www/html/snipeit/deploy/deploy.sh "$TAG"

      # If key step failed, fall back to PASSWORD
      - name: Deploy over SSH (password fallback)
        if: steps.ssh_key.outcome == 'failure'
        uses: appleboy/ssh-action@v1.2.1
        env:
          TAG: ${{ github.ref_name }}
          APP_DIR: /var/www/html/snipeit
          REPO_URL:  git@github.com:BZ1884/snipe-it.git
          PHP_FPM_SERVICE: php8.3-fpm   # adjust if needed
          APACHE_SERVICE: apache2
          KEEP_RELEASES: "5"
        with:
            host: ${{ secrets.DEPLOY_HOST }}
            username: ${{ secrets.DEPLOY_USER }}
            port: ${{ secrets.DEPLOY_PORT }}
            password: ${{ secrets.DEPLOY_PASSWORD }}  # strong, rotated
            script_stop: true
            envs: TAG,APP_DIR,REPO_URL,PHP_FPM_SERVICE,APACHE_SERVICE,KEEP_RELEASES
            script: |
              bash /var/www/html/snipeit/deploy/deploy.sh "$TAG"
